[package]
name = "ui"
version = "0.0.1"
edition = "2018"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]

[dependencies]
boxfuture = { path = "../boxfuture" }
futures = "0.1.27"
futures-locks = "0.5"
lazy_static = "1"
rand = "0.5.1"
termion = "1.5.5"
unicode-segmentation = "1.6.0"
