[package]
version = "0.0.1"
name = "boxfuture"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]

[dependencies]
futures = { path = "/Users/stuhood/src/futures-rs" }

[patch.crates-io]
futures = { path = "/Users/stuhood/src/futures-rs" }
